sudo pip uninstall keras==2.2.5
sudo pip uninstall h5py
sudo pip uninstall opencv-python
sudo apt-get uninstall tmux
sudo apt-get uninstall libsm6
sudo apt-get uninstall libxrender1
sudo apt-get uninstall libxext-dev
sudo pip uninstall moviepy
sudo apt uninstall python3-tk
sudo apt-get uninstall ffmpeg
sudo pip uninstall pandas
sudo pip uninstall sklearn
sudo pip uninstall matplotlib
